version: "3.9"

services:
    backend:
        build:
            context: ./backend
        working_dir:
            - /app
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app